allowBuilds:
  "@google/genai": true
  "@prisma/engines": true
  bcrypt: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  unrs-resolver: true

  minimumReleaseAgeExclude:
    - openai@7.30.1